site_name: GoElites Wiki
repo_url: https://github.com/y1n/GoElites.Wiki
pages:
- Home: index.md
- Principles:
    - Community Guidelines: Community Principles/Community Guidelines.md
    - Support Guidelines: Community Principles/Support Guidelines.md
- Getting Started:
    - Installing GoElites: Getting Started/Installation.md
    - Features: Getting Started/Features.md
    - FAQ: Getting Started/FAQ.md
- Troubleshooting:
    - How to submit a support ticket: Troubleshooting/Troubleshooting Report Guide.md
    - Website Troubleshooting: Troubleshooting/Website Troubleshooting.md
    - Application Troubleshooting: Troubleshooting/Application Troubleshooting.md

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'pink'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'