site_name: GoElites Wiki
repo_url: https://github.com/y1n/GoElites.Wiki
pages:
- Home: index.md
- Principles:
    - Community Guidelines: CommunityPrinciples/CommunityGuidelines.md
    - Support Guidelines: CommunityPrinciples/SupportGuidelines.md
- Getting Started:
    - Installing GoElites: GettingStarted/Installation.md
    - Features: GettingStarted/Features.md
    - Supported Champions: GettingStarted/SupportedChampions.md
    - FAQ: Getting Started/FAQ.md
- Troubleshooting:
    - How to submit a support ticket: Troubleshooting/TroubleshootingReportGuide.md
    - Website Troubleshooting: Troubleshooting/WebsiteTroubleshooting.md
    - Application Troubleshooting: Troubleshooting/ApplicationTroubleshooting.md
    
theme: readthedocs